site_name: srs-secure-rag
site_description: SRS Secure RAG

nav:
  - Home: index.md
  - Introduction: 
      - Purpose of the Document: introduction/purpose-of-the-document.md
      - Scope: introduction/scope.md
      - Definitions and Acronyms: introduction/definitions-and-acronyms.md
  - Description:
      - Product Overview: description/product-overview.md
      - Product Features: description/product-features.md
  - Interface Requirement:
      - Communication Interface: interface-requirement/communication-interface.md
      - Software Interface and Stack: interface-requirement/software-interface-and-stack.md
  - Functional Requirement:
    - Functional Requirement Table: functional-requirement/functional-requirement-table.md
    - Activity or Use Case Diagram: functional-requirement/activity-or-use-case-diagram.md
  - Charging and Billing:
      - Charging and Billing: charging-and-billing/charging-and-billing.md
  - Non-Functional Requirements:
      - Non-Functional Requirements: non-functional-requirements/non-functional-requirements.md
  - Appendix:
      - Appendix: appendix/appendix.md

theme:
  name: material

plugins:
  - techdocs-core
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css 
